version: "3.9"

services:
  db:
    image: postgres
    volumes:
      - /db:/var/lib/postgresql/data
    environment:
      POSTGRES_DB: auction_site
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_HOST: localhost
      POSTGRES_PORT: 5432

  backend:
    build:
      context: ./backend/
      dockerfile: Dockerfile
    container_name: backend
    volumes:
      - ./backend/:/app
    network_mode: "host"
    depends_on:
      - db

  frontend:
    build:
      context: ./frontend/
      dockerfile: Dockerfile
    container_name: frontend
    volumes:
      - ./frontend/:/app
      - /app/node_modules
    stdin_open: true
    network_mode: "host"
    depends_on:
      - backend