# Generated by Django 4.1 on 2022-09-03 08:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0003_alter_auction_latitude_alter_auction_longitude'),
    ]

    operations = [
        migrations.AlterField(
            model_name='auction',
            name='ends',
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name='auction',
            name='started',
            field=models.DateTimeField(),
        ),
    ]
