# Generated by Django 4.1 on 2022-09-03 14:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0005_rename_categories_auction_category'),
    ]

    operations = [
        migrations.RenameField(
            model_name='category',
            old_name='tag',
            new_name='category',
        ),
    ]
