# Generated by Django 4.1 on 2022-09-03 14:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0008_alter_auction_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='auction',
            name='category',
            field=models.ManyToManyField(to='auctions.category'),
        ),
    ]
