# Generated by Django 4.1 on 2022-09-12 11:35

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0011_alter_category_options_auctionimage'),
    ]

    operations = [
        migrations.AddField(
            model_name='auctionimage',
            name='order',
            field=models.IntegerField(default=1, validators=[django.core.validators.MinValueValidator(1)]),
        ),
        migrations.AddConstraint(
            model_name='auctionimage',
            constraint=models.UniqueConstraint(fields=('order', 'auction'), name='unique_image_order'),
        ),
    ]
