# Generated by Django 4.1 on 2022-09-16 14:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0012_auctionimage_order_auctionimage_unique_image_order'),
    ]

    operations = [
        migrations.AlterField(
            model_name='auctionimage',
            name='image',
            field=models.ImageField(upload_to='auction_images'),
        ),
    ]
