# Generated by Django 4.1 on 2022-09-26 09:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0017_alter_auctionimage_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='auction',
            name='first_bid',
            field=models.DecimalField(decimal_places=2, max_digits=6),
        ),
        migrations.AlterField(
            model_name='bid',
            name='amount',
            field=models.DecimalField(decimal_places=2, max_digits=6),
        ),
    ]
