# Generated by Django 4.1 on 2022-08-12 16:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_appuser_is_approved_alter_appuser_email_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appuser',
            name='is_approved',
            field=models.BooleanField(default=False),
        ),
    ]
