# Generated by Django 4.1 on 2022-08-17 15:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_alter_baseuser_is_superuser'),
    ]

    operations = [
        migrations.DeleteModel(
            name='AppAdmin',
        ),
    ]
