# Generated by Django 4.1 on 2022-08-24 11:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0010_alter_baseuser_email_alter_baseuser_first_name_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='appuser',
            options={},
        ),
        migrations.AlterModelOptions(
            name='baseuser',
            options={},
        ),
    ]
